/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Ventanas;

import Clases.CCP;
import java.time.LocalDate;
import java.util.Date;
import javax.swing.JMenuItem;
import javax.swing.JOptionPane;

/**
 *
 * @author Yoselin
 */
public class Dia extends javax.swing.JFrame {

    private CCP ccp;
    public static Date fe;
    public static Hora ventana = null;

    /**
     * Creates new form Dia
     */
    public Dia(CCP c) {
        this.ccp = c;
        initComponents();
        this.setLocationRelativeTo(null);

    }
    CamaraGUI cg = new CamaraGUI(ccp);
    Salon ven = cg.v;

//    Salon s = new Salon(ccp);
//    Salones sele = s.sa;
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Calend = new com.toedter.calendar.JCalendar();
        btnAnterior = new javax.swing.JButton();
        Siguiente = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        btnAnterior.setText("Anterior");
        btnAnterior.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAnteriorActionPerformed(evt);
            }
        });

        Siguiente.setText("Siguiente");
        Siguiente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SiguienteActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(45, 45, 45)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btnAnterior)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(Siguiente))
                    .addComponent(Calend, javax.swing.GroupLayout.PREFERRED_SIZE, 397, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(45, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addComponent(Calend, javax.swing.GroupLayout.PREFERRED_SIZE, 239, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 37, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnAnterior)
                    .addComponent(Siguiente))
                .addGap(29, 29, 29))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void SiguienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SiguienteActionPerformed

        Date fecha = Calend.getDate();

        if (((fecha.getYear() + 1900 == LocalDate.now().getYear())
                && (fecha.getMonth() + 1 == LocalDate.now().getMonthValue())
                && (fecha.getDate() > LocalDate.now().getDayOfMonth()))
                || ((fecha.getYear() + 1900 == LocalDate.now().getYear())
                && (fecha.getMonth() + 1 > LocalDate.now().getMonthValue()))
                || (fecha.getYear() + 1900 > LocalDate.now().getYear())) {
            fe = fecha;
            this.ventana = new Hora(ccp);
            this.ventana.setResizable(false);
            dispose();
            ventana.setVisible(true);
        } else {
            JOptionPane.showMessageDialog(null, "Selecione una fecha correcta");
        }
        System.out.println(fe);
    }//GEN-LAST:event_SiguienteActionPerformed


    private void btnAnteriorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAnteriorActionPerformed
        dispose();
        ven.setVisible(true);
    }//GEN-LAST:event_btnAnteriorActionPerformed

    /**
     * @param args the command line arguments
     */
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private com.toedter.calendar.JCalendar Calend;
    private javax.swing.JButton Siguiente;
    private javax.swing.JButton btnAnterior;
    // End of variables declaration//GEN-END:variables

}
