/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Ventanas;

import Clases.CCP;
import Clases.Cliente;
import Clases.Evento;
import Clases.Reservacion;
import Clases.Salones;
import Clases.TipoCliente;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.sql.Time;
import java.text.SimpleDateFormat;
import java.time.LocalDate;
import java.time.LocalTime;
import java.time.ZoneId;
import java.util.Date;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.ComboBoxModel;
import javax.swing.JOptionPane;
import javax.swing.event.ListDataListener;

/**
 *
 * @author Yoselin
 */
public class Reservaciones extends javax.swing.JFrame {

    private CCP ccp;
    private Cliente c1 = null;
    private Salones s;
    private String Hora1, Hora2;
    private Date fecha;

    /**
     * Creates new form Reservacion
     */
    public Reservaciones(CCP c, String h1, String h2, Salones salon, Date date1) {
        this.ccp = c;
        initComponents();
        this.setLocationRelativeTo(null);
        Hora1 = h1;
        Hora2 = h2;
        hinicio.setText(h1);
        Fin.setText(h2);
        hinicio.setEditable(false);
        Fin.setEditable(false);
        TxtSalon.setText(salon.getNombre());
        TxtSalon.setEditable(false);
        s = salon;
        manejadorregistraEvento mv = new manejadorregistraEvento();
        RegistrarBu.addActionListener(mv);
        System.out.println(date1);

        Date date = Date.from(LocalDate.now().atStartOfDay(ZoneId.systemDefault()).toInstant());
        SimpleDateFormat sdf = new SimpleDateFormat("dd-MM-yyyy");
        String fechaCadena = sdf.format(date);
        fecha = date1;
        String fechaCadenap = sdf.format(date1);

        System.out.println("Hora " + fecha);
        FechaSolicitud.setText(fechaCadena);
        FechaProgra.setText(fechaCadenap);
        FechaProgra.setEditable(false);

        FechaSolicitud.setEditable(false);
        ManejadorBuscar mb = new ManejadorBuscar();
        BuscarBoton.addActionListener(mb);
        ManejadorComboBox mj = new ManejadorComboBox();
        jComboBox1.setModel(mj);

        manejadorcancelar mc = new manejadorcancelar();
        CancelarB.addActionListener(mc);
    }

    Dia d = new Dia(ccp);
    Hora h = d.ventana;

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTextField12 = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        FechaSolicitud = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        Telefono = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        CC = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        NombreSol = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        jComboBox1 = new javax.swing.JComboBox<>();
        BuscarBoton = new javax.swing.JButton();
        jLabel19 = new javax.swing.JLabel();
        Email = new javax.swing.JTextField();
        jPanel2 = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        NumeroAsistente = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        Respon = new javax.swing.JTextField();
        NombreEven = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        IDRes = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        FechaProgra = new javax.swing.JTextField();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        hinicio = new javax.swing.JTextField();
        Fin = new javax.swing.JTextField();
        TxtSalon = new javax.swing.JTextField();
        jPanel3 = new javax.swing.JPanel();
        Him = new javax.swing.JCheckBox();
        Mante = new javax.swing.JCheckBox();
        Micro = new javax.swing.JCheckBox();
        mesa = new javax.swing.JCheckBox();
        Telon = new javax.swing.JCheckBox();
        Port = new javax.swing.JCheckBox();
        señali = new javax.swing.JCheckBox();
        Video = new javax.swing.JCheckBox();
        jComboBox3 = new javax.swing.JComboBox<>();
        jLabel16 = new javax.swing.JLabel();
        jLabel26 = new javax.swing.JLabel();
        pape = new javax.swing.JCheckBox();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        jLabel23 = new javax.swing.JLabel();
        jLabel24 = new javax.swing.JLabel();
        jLabel25 = new javax.swing.JLabel();
        CancelarB = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        RegistrarBu = new javax.swing.JButton();

        jTextField12.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField12ActionPerformed(evt);
            }
        });

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setBackground(new java.awt.Color(0, 0, 0));
        jLabel1.setFont(new java.awt.Font("Arial Black", 0, 14)); // NOI18N
        jLabel1.setText("Reservacion De Salas Y Auditorios");

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder("Informacion Solicitud"));

        jLabel2.setText("Fecha Solicitud:");

        FechaSolicitud.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                FechaSolicitudActionPerformed(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Arial Black", 0, 11)); // NOI18N
        jLabel3.setText("Solicitante");

        Telefono.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TelefonoActionPerformed(evt);
            }
        });

        jLabel4.setText("Telefono:");

        CC.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CCActionPerformed(evt);
            }
        });

        jLabel8.setText("N° ID:");

        jLabel9.setText("Nombre:");

        NombreSol.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                NombreSolActionPerformed(evt);
            }
        });

        jLabel11.setText("Tipo Solicitante:");

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        jComboBox1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox1ActionPerformed(evt);
            }
        });

        BuscarBoton.setText("Buscar");

        jLabel19.setText("Email:");

        Email.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EmailActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(jLabel8)
                                .addComponent(jLabel3)
                                .addComponent(jLabel9)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(FechaSolicitud, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(NombreSol, javax.swing.GroupLayout.DEFAULT_SIZE, 130, Short.MAX_VALUE)
                                    .addComponent(CC))
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGap(18, 18, 18)
                                        .addComponent(BuscarBoton, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGap(32, 32, 32)
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel4)
                                            .addComponent(jLabel19))
                                        .addGap(18, 18, 18)
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addComponent(Telefono, javax.swing.GroupLayout.DEFAULT_SIZE, 120, Short.MAX_VALUE)
                                            .addComponent(Email))))))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel11)
                            .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, 209, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 0, Short.MAX_VALUE))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(FechaSolicitud, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel3)
                .addGap(0, 0, 0)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(CC, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel8)
                    .addComponent(BuscarBoton))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(NombreSol)
                    .addComponent(jLabel9)
                    .addComponent(jLabel4)
                    .addComponent(Telefono, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel11)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel19)
                            .addComponent(Email, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addContainerGap())))
        );

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder("Informacion Evento"));

        jLabel7.setText("N° Asistentes:");

        NumeroAsistente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                NumeroAsistenteActionPerformed(evt);
            }
        });

        jLabel10.setText("Salon:");

        Respon.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ResponActionPerformed(evt);
            }
        });

        NombreEven.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                NombreEvenActionPerformed(evt);
            }
        });

        jLabel5.setText("Nombre Del Evento:");

        jLabel6.setText("Responsable Del Evento:");

        jLabel12.setText("N° ID:");

        IDRes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                IDResActionPerformed(evt);
            }
        });

        jLabel13.setText("Fecha:");

        FechaProgra.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                FechaPrograActionPerformed(evt);
            }
        });

        jLabel14.setText("H. Inicio:");

        jLabel15.setText("H. Fin:");

        TxtSalon.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TxtSalonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                            .addComponent(jLabel5)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(NombreEven, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                            .addComponent(jLabel6)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addComponent(Respon, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                            .addComponent(jLabel7)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(NumeroAsistente, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel10)
                        .addGap(18, 18, 18)
                        .addComponent(TxtSalon, javax.swing.GroupLayout.PREFERRED_SIZE, 178, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(32, 32, 32)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel12)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(IDRes, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel13)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(FechaProgra, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(jLabel15)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(Fin, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(1, 1, 1))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(jLabel14)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(hinicio, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(Respon, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel12)
                    .addComponent(IDRes, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(NombreEven, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel13)
                    .addComponent(FechaProgra, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(NumeroAsistente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel14)
                    .addComponent(hinicio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel15)
                        .addComponent(Fin, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel10)
                        .addComponent(TxtSalon, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(46, Short.MAX_VALUE))
        );

        jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder("Infromacion Implementos"));

        jComboBox3.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        jLabel16.setText("Himnos:");

        jLabel26.setText("Papelografo:");

        jLabel17.setText("Manteles:");

        jLabel18.setText("Mesas:");

        jLabel20.setText("Microfono:");

        jLabel21.setText("Telon:");

        jLabel22.setText("Señalizador:");

        jLabel23.setText("Video Beam:");

        jLabel24.setText("Portatil:");

        jLabel25.setText("Silleteria:");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(jLabel25)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jComboBox3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(366, 366, 366))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel17)
                            .addComponent(jLabel16)
                            .addComponent(jLabel26))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(Him)
                            .addComponent(Mante)
                            .addComponent(pape))
                        .addGap(68, 68, 68)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel20)
                            .addComponent(jLabel18, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel21, javax.swing.GroupLayout.Alignment.TRAILING))
                        .addGap(6, 6, 6)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                                .addComponent(mesa)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabel22))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                                .addComponent(Micro)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabel24))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                                .addComponent(Telon)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabel23)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(Port)
                            .addComponent(señali)
                            .addComponent(Video))
                        .addGap(120, 120, 120))))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel16)
                    .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel20)
                        .addComponent(jLabel24))
                    .addComponent(Port)
                    .addComponent(Him)
                    .addComponent(Micro))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(Mante)
                    .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel18)
                        .addComponent(jLabel17)
                        .addComponent(jLabel22))
                    .addComponent(mesa)
                    .addComponent(señali))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel21)
                        .addComponent(jLabel23)
                        .addComponent(jLabel26))
                    .addComponent(Telon)
                    .addComponent(Video)
                    .addComponent(pape))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel25)
                    .addComponent(jComboBox3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        CancelarB.setText("Cancelar");

        jButton3.setText("Anterior");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        RegistrarBu.setText("Registrar");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jPanel2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(129, 129, 129)
                        .addComponent(jLabel1)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jButton3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(RegistrarBu)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(CancelarB)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(CancelarB)
                    .addComponent(jButton3)
                    .addComponent(RegistrarBu))
                .addContainerGap(16, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void FechaSolicitudActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_FechaSolicitudActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_FechaSolicitudActionPerformed

    private void TelefonoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TelefonoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TelefonoActionPerformed

    private void CCActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CCActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_CCActionPerformed

    private void NombreSolActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_NombreSolActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_NombreSolActionPerformed

    private void ResponActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ResponActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ResponActionPerformed

    private void NombreEvenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_NombreEvenActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_NombreEvenActionPerformed

    private void NumeroAsistenteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_NumeroAsistenteActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_NumeroAsistenteActionPerformed

    private void IDResActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_IDResActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_IDResActionPerformed

    private void jTextField12ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField12ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField12ActionPerformed

    private void FechaPrograActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_FechaPrograActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_FechaPrograActionPerformed

    private void jComboBox1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBox1ActionPerformed

    private void TxtSalonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TxtSalonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TxtSalonActionPerformed

    private void EmailActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EmailActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_EmailActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed

        dispose();
        h.setVisible(true);
    }//GEN-LAST:event_jButton3ActionPerformed

    /**
     * @param args the command line arguments
     */

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BuscarBoton;
    private javax.swing.JTextField CC;
    private javax.swing.JButton CancelarB;
    private javax.swing.JTextField Email;
    private javax.swing.JTextField FechaProgra;
    private javax.swing.JTextField FechaSolicitud;
    private javax.swing.JTextField Fin;
    private javax.swing.JCheckBox Him;
    private javax.swing.JTextField IDRes;
    private javax.swing.JCheckBox Mante;
    private javax.swing.JCheckBox Micro;
    private javax.swing.JTextField NombreEven;
    private javax.swing.JTextField NombreSol;
    private javax.swing.JTextField NumeroAsistente;
    private javax.swing.JCheckBox Port;
    private javax.swing.JButton RegistrarBu;
    private javax.swing.JTextField Respon;
    private javax.swing.JTextField Telefono;
    private javax.swing.JCheckBox Telon;
    private javax.swing.JTextField TxtSalon;
    private javax.swing.JCheckBox Video;
    private javax.swing.JTextField hinicio;
    private javax.swing.JButton jButton3;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JComboBox<String> jComboBox3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JTextField jTextField12;
    private javax.swing.JCheckBox mesa;
    private javax.swing.JCheckBox pape;
    private javax.swing.JCheckBox señali;
    // End of variables declaration//GEN-END:variables

    private int si = 20;

    public class ManejadorBuscar implements ActionListener {

        @Override
        public void actionPerformed(ActionEvent e) {
            try {
                c1 = null;
                Long identificacion = Long.parseLong(CC.getText());
                Cliente c = ccp.buscarCliente(identificacion);
                c1 = c;
                Cliente C2 = c;
                NombreSol.setText(c.getNombres());
                NombreSol.setEditable(false);
                Telefono.setText(Long.toString(c.getTelefono()));
                Telefono.setEditable(false);
                Email.setText(c1.getEmail());
                Email.setEditable(false);
                selecionado = c.getTipo_cliente();
                jComboBox1.updateUI();
                jComboBox1.enable(false);

                if (c1 == null) {
                    int ms = JOptionPane.showConfirmDialog(null, "El Solicitante Con Numero " + CC.getText()
                            + " No Se Encuentra Registrado ¿ desea Registrarlo ?",
                            "Cliente No Encontado",
                            JOptionPane.YES_NO_OPTION, JOptionPane.QUESTION_MESSAGE);
                }

            } catch (NumberFormatException nfe) {
                JOptionPane.showMessageDialog(null, "Ingrese Un Codigo Valido");
            } catch (IllegalArgumentException iae) {
                JOptionPane.showMessageDialog(null, iae.getMessage());
            } catch (Exception ex) {
                if (c1 == null) {
                    si = JOptionPane.showConfirmDialog(null, "El Solicitante Con Numero " + CC.getText()
                            + " No Se Encuentra Registrado ¿ desea Registrarlo ?",
                            "Cliente No Encontado",
                            JOptionPane.YES_NO_OPTION, JOptionPane.QUESTION_MESSAGE);
                    if (si == JOptionPane.NO_OPTION) {
                        JOptionPane.showMessageDialog(null, ex.getMessage());
                    } else {
                        NombreSol.setEditable(true);
                        Telefono.setEditable(true);
                        Email.setEditable(true);
                        Email.setText("");
                        NombreSol.setText("");
                        Telefono.setText("");
                        selecionado = null;
                        jComboBox1.enable(true);
                        jComboBox1.updateUI();
                        JOptionPane.showMessageDialog(null, "El Cliente Sera Registrado Al Finalizar El Registro");
                    }

                }

            }
        }
    }
    private Object selecionado = null;

    public class ManejadorComboBox implements ComboBoxModel {

        @Override
        public void setSelectedItem(Object anItem) {
            selecionado = anItem;
        }

        @Override
        public Object getSelectedItem() {
            return selecionado;
        }

        @Override
        public int getSize() {
            return ccp.getTipoClientes().size();
        }

        @Override
        public Object getElementAt(int index) {
            return ccp.getTipoClientes().get(index);
        }

        @Override
        public void addListDataListener(ListDataListener l) {
        }

        @Override
        public void removeListDataListener(ListDataListener l) {
        }
    }

    public class manejadorregistraEvento implements ActionListener {

        @Override
        public void actionPerformed(ActionEvent e) {

            try {
                String nombreRe = Respon.getText();
                Long Id = Long.parseLong(IDRes.getText());
                String EventoNo = NombreEven.getText();
                int sillet = Integer.parseInt(NumeroAsistente.getText());
                LocalDate Programada = fecha.toInstant().atZone(ZoneId.systemDefault()).toLocalDate();
                Evento ev = new Evento(EventoNo, nombreRe, sillet, Id, s);
                if (Him.isSelected()) {
                    ev.setHimnos(true);
                }
                if (Micro.isSelected()) {
                    ev.setMicrofono(true);
                }
                if (Port.isSelected()) {
                    ev.setPortatil(true);
                }
                if (Mante.isSelected()) {
                    ev.setManteles(true);
                }
                if (mesa.isSelected()) {
                    ev.setMesas(true);
                }
                if (señali.isSelected()) {
                    ev.setSeñalizador(true);
                }
                if (pape.isSelected()) {
                    ev.setSeñalizador(true);
                }
                if (Telon.isSelected()) {
                    ev.setSeñalizador(true);
                }
                if (Video.isSelected()) {
                    ev.setVideo_beam(true);
                }
                System.out.println(si);
                if (si == JOptionPane.YES_OPTION) {
                    String no = NombreSol.getText();
                    Long cc = Long.parseLong(CC.getText());
                    String Ema = Email.getText();
                    Long Te = Long.parseLong(Telefono.getText());
                    TipoCliente Ts = (TipoCliente) jComboBox1.getSelectedItem();

                    c1 = new Cliente(Ema, Te, cc, no, Ts);
                    ccp.AgregarCliente(c1);
                    JOptionPane.showMessageDialog(null, "El Solicitante " + c1.getNombres() + "Ha Sido Registrado");

                }
                int ms = JOptionPane.showConfirmDialog(null, "¿Desea Registrar La Reservacion Del Solicitante  "
                        + c1.getNombres() + " Para El Dia " + Programada + " En El Salon " + ev.getSalon().getNombre() + "?",
                        "Confirmar Reservacion",
                        JOptionPane.YES_NO_OPTION, JOptionPane.QUESTION_MESSAGE);

                //System.out.println( "Evento " + rs.getEvento().isHimnos());
                if (ms == JOptionPane.YES_OPTION) {

                    Reservacion rs = new Reservacion(c1, ev, LocalTime.parse(Hora1), LocalTime.parse(Hora1),
                            Programada);
                    ccp.AgregarReservacion(rs);
                    JOptionPane.showMessageDialog(null, "Se Ha Registrado La reservacion Con Exito");
                    //BorrarCampos
                    Respon.setText("");
                    IDRes.setText("");
                    NombreEven.setText("");
                    NumeroAsistente.setText("");
                    NombreSol.setText("");
                    CC.setText("");
                    Telefono.setText("");
                    selecionado = null;
                    jComboBox1.enable(true);
                    jComboBox1.updateUI();
                    Micro.setSelected(false);
                    Him.setSelected(false);
                    Port.setSelected(false);
                    Mante.setSelected(false);
                    mesa.setSelected(false);
                    señali.setSelected(false);
                    pape.setSelected(false);
                    Telon.setSelected(false);
                    Video.setSelected(false);
                    Email.setText("");
                } else {
                 //  JOptionPane.showMessageDialog(null, "Debe Agragar Nuevamentte El Cliente");

//                    NombreSol.setEditable(true);
//
//                    Telefono.setEditable(true);
//
//                    Email.setEditable(true);
//
//                    NombreSol.setText("");
//                    CC.setText("");
//                    Telefono.setText("");
//                    selecionado = null;
//                    jComboBox1.enable(true);
//                    jComboBox1.updateUI();
//                    c1 = null;
                }

            } catch (NumberFormatException nfe) {
                JOptionPane.showMessageDialog(null, "Dato Numerico Invalido");
            } catch (Exception ex) {

                if (ex.getMessage().equalsIgnoreCase("For input string: \"\"")) {
                    JOptionPane.showMessageDialog(null, "Campos Obligatorios Sin Rellenar");
                } else {
                    JOptionPane.showMessageDialog(null, ex.getMessage());
                    System.out.println(ex.getMessage());
                }

            }

        }
    }

    public class manejadorcancelar implements ActionListener {

        @Override
        public void actionPerformed(ActionEvent e) {
            Respon.setText("");
            IDRes.setText("");
            NombreEven.setText("");
            NumeroAsistente.setText("");
            NombreSol.setText("");
            CC.setText("");
            Telefono.setText("");
            selecionado = null;
            jComboBox1.enable(true);
            jComboBox1.updateUI();
            Micro.setSelected(false);
            Him.setSelected(false);
            Port.setSelected(false);
            Mante.setSelected(false);
            mesa.setSelected(false);
            señali.setSelected(false);
            pape.setSelected(false);
            Telon.setSelected(false);
            Video.setSelected(false);
            Email.setText("");
            Email.setEditable(true);
            si = 20;
            c1 = null;
            Telefono.setEditable(true);
            NombreSol.setEditable(true);

        }

    }

}
